author: 若离|IceTiki|https://github.com/IceTiki/ruoli-sign-optimization
# YAML有引用和锚点，可以节省配置长度(备注:锚点要放在引用的前面)(可以参考https://www.runoob.com/w3cnote/yaml-intro.html)
# ======================================================================
# 全局设置
# ======================================================================
locationOffsetRange: 50 # 坐标偏移范围(单位：米)(可以为0)
maxTry: 1 # 最大尝试次数
logDir: 'log/' # 日志保存地址
delay: [5,10] # 多用户时，各用户之间任务执行延迟(时间范围可以使用浮点数)
sendMessage: # 推送函数的整体运行情况
  rl_emailApiUrl: http://mail.ruoli.cc/api/sendMail # 邮箱API的地址(不需要推送不用填)
  rl_email: "" # email 接受通知消息的邮箱(不需要推送不用填)
  qmsg_key: "" # qmsg推送的key(不需要推送不用填)
  qmsg_qq: "" # qmsg推送的qq号(不需要推送不用填)
  qmsg_isGroup: 0 # 此qq号是否为群(是的话填1，反之为0)
  pushplus_token: "" # pushplus令牌
  smtp_host: "smtp.qq.com" # SMTP服务器域名
  smtp_user: "*****@qq.com" # SMTP服务器用户名
  smtp_key: "" # SMTP服务器密钥
  smtp_sender: "*****@qq.com" # 发送邮箱
  smtp_receivers:
    - "*****@qq.com" # 接收邮箱(可填多个)
# ======================================================================
# 用户组配置(填写自己所需的类型，并删掉不需要的。可以多用户签到。)
# ======================================================================
users: # ------别误删了这一行------
  - # 信息收集模板=======
    # 通用必填项-------
    type: 0 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 宜宾学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    checkTitle: 1 # 是否检查表单的标题（1:检查|0:不检查）
    forms: # 表单信息
      - form:
          title: 今日具体所在地
          value: 四川省/宜宾市/翠屏区 # 如果是多选请用"|"分割值
          isNeed: 1 # 是否需要提交此问题，必填问题一定要填1(1:提交|0:不提交)
      - form:
          title: 是否在校
          value: 是
          isNeed: 1
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 104.616858 # 经度
    lat: 28.793022 # 纬度
    address: "宜宾市（自己改）" # 地址信息

  - # 签到模板=======
    # 通用必填项-------
    type: 1 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 宜宾学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: sign.jpg # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    title: 0 # 签到任务的标题[0:自动取最后一个未签到的任务]
    checkTitle: 1 # 是否检查表单各项的标题[1:检查|0:不检查]
    signLevel: 1 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    forms: # 表单信息
      - form:
          title: 今天你的体温是多少？
          value: 37.2℃及以下
      - form:
          title: 今天你的身体状况是？
          value: 健康
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 104.616858 # 经度
    lat: 28.793022 # 纬度
    address: "宜宾市（自己改）" # 地址信息

  - # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 宜宾学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: sign.jpg # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 104.616858 # 经度
    lat: 28.793022 # 纬度
    address: "宜宾市（自己改）" # 地址信息

  - # 教师工作日志模板=======
    # 通用必填项-------
    type: 3 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 宜宾学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    checkTitle: 1 # 是否检查表单的标题（1:检查|0:不检查）
    forms: # 表单信息
      - form:
          title: 2.是否在校上班或居住
          value: 是
      - form:
          title: 3.上午体温
          value: 36.2
      - form:
          title: 4.下午体温
          value: 36.4
      - form:
          title: 5.晚上体温
          value: 36.1
      - form:
          title: 6.身体状况
          value: 身体健康
      - form:
          title: 7.是否请假
          value: 否
      - form:
          title: 8.今日是否返回宜宾市
          value: 否
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 104.616858 # 经度
    lat: 28.793022 # 纬度
    address: "宜宾市（自己改）" # 地址信息

  - # 政工签到模板=======
    # 通用必填项-------
    type: 4 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 宜宾学院 # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: sign.jpg # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 104.616858 # 经度
    lat: 28.793022 # 纬度
    address: "宜宾市（自己改）" # 地址信息